# Generated by Django 4.0.6 on 2022-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('deleted', 'deleted'), ('triggered', 'triggered')], default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
